name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "image-scramble"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          healthcheck: "https://image-scramble.herokuapp.com/ok"
          checkstring: "computer"
          delay: 5
          rollbackonhealthcheckfailed: true
